name: Run tests for django

on: [push]

jobs:
  homework-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest Faker requests pytest-asyncio
    - name: Install inner (homework-level) dependencies
      run: |
        for d in homework_10 ; do
          HW_REQUIREMENTS_PATH="$d/requirements.txt"
            if [ -f "$HW_REQUIREMENTS_PATH" ];
            then
              echo file \'"$HW_REQUIREMENTS_PATH"\' exists, installing...
              pip install -r "$HW_REQUIREMENTS_PATH";
            fi
        done
    - name: Test django
      working-directory: homework_10/homework07
      run: |
        python manage.py test
